### ISSUE TITLE
how to build dynamic expression sort ?

### ISSUE THREAD

**Issue by liu2510865** [harshwPro/EntityFrameworkPaginate#2]
when i am add sort condition,i just know entity property, so i don't know how write the generic type of TKey...

**Comment by harshwPro** [comment]
You need to define an entity for the Sorts object to apply the sorting. It is strongly typed.
Can you please share some code so that i can better understand what you are trying to achieve?

**Comment by liu2510865** [comment]
like this
 
 `
public JsonResult GetData(Activity model)
        {
 
            Sorts<jhj_activity> sorts = new Sorts<jhj_activity>();
            sorts.Add(string.IsNullOrEmpty(sort), LambdaHelper.GetOrderExpression<jhj_activity, DateTime?>("add_time"), true);
            if (!string.IsNullOrEmpty(sort))
                sorts.Add(true, LambdaHelper.GetOrderExpression<jhj_activity, string>(sort), order == null ? false : order == "desc" ? true : false);
            Page<jhj_activity> re = appActiveManager.GetList(filters, sorts, pageSize, pageNumber);
            return Json(re);
        }
`
when i get sort field from ui,i mast build this ` Expression<Func<T, TKey>> expression`  add to sorts,but sort expression need TKey , so  i  don't know how to  build dynamic expression for sort..

e. i want Dynamic sort using EntityFrameworkPaginate.


thinks!
