### ISSUE TITLE
Entityframework Paginate error

### ISSUE THREAD

**Issue by gabrielhmo** [harshwPro/EntityFrameworkPaginate#5]
Hello, this is really great. Thanks for share.

I tried step by step as explained in the tutorial but I get this error:

The method 'Skip' is only supported for sorted input in LINQ to Entities. The method 'OrderBy' must be called before the method 'Skip'.

To resolve this I had to put the sort expression before Paginate

dbContext.Entity.OrderBy(OrderByExpression).Paginate(parameters.PageNumber, parameters.PageSize, sorts, filter);

Thanks again.

**Comment by harshwPro** [comment]
Hi @gabrielhmo Did you set the conditional sorts? Having set that won't require you to use order by. But if you don't have conditional order by, you can always use order by directly.
