### ISSUE TITLE
OrderBy and ThenBy

### ISSUE THREAD

**Issue by snu-smumrik** [harshwPro/EntityFrameworkPaginate#6]
Hello,
I would like to use sorting by two or more columns, is it possible?

**Comment by harshwPro** [comment]
Hi aUdalov, 
Sorting using multiple columns is currently not supported. But looks like a good enhancement. I will be working on the changes and update you as its completed.
By the way, can you elaborate on the use case? When you try to sort based on multiple columns, do you have a process through which you decide the sequence of the sorting columns?

**Comment by harshwPro** [comment]
Hi @aUdalov 

The changes for this feature is now published. 
You can upgrade your [NuGet package](https://www.nuget.org/packages/EntityFrameworkPaginate/1.2.0) to access the feature.
The tutorial/documentation is available [here](http://harshw.com/sorting-multiple-columns-using-entity-framework-paginate/).

Hope this helps.

Thanks,
Harsh
