### ISSUE TITLE
Getting error without sorting and filtering?

### ISSUE THREAD

**Issue by RahmanM** [harshwPro/EntityFrameworkPaginate#8]
Hello,

I am trying to paginate the result of my query however I am getting the following error:

"Exception thrown: 'System.NotSupportedException' in EntityFramework.SqlServer.dll
Additional information: The method 'Skip' is only supported for sorted input in LINQ to Entities. The method 'OrderBy' must be called before the method 'Skip'. occurred"

I am using this overload:

Page<Todo> pagination = context.Todoes.Paginate(1, 10);

Packages:

```
  <package id="EntityFramework" version="6.2.0" targetFramework="net461" />
  <package id="EntityFrameworkPaginate" version="1.2.0" targetFramework="net461" />
```

Shouldn't it work?

Rahman

**Comment by harshwPro** [comment]
@RahmanM You need to provide at least `Sort` object. This initializes the `orderby`, without which pagination does not work.
